apiVersion: v1
kind: Config
clusters:
- name: "cluster1"
  cluster:
    server: "https://ec2-35-171-107-155.compute-1.amazonaws.com/k8s/clusters/c-m-b5922jp7"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ2RENDQ\
      VdPZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQkdNUnd3R2dZRFZRUUtFeE5rZVc1aGJXbGoKY\
      kdsemRHVnVaWEl0YjNKbk1TWXdKQVlEVlFRRERCMWtlVzVoYldsamJHbHpkR1Z1WlhJdFkyRkFNV\
      GN5T1RnNQpNRGd4TXpBZUZ3MHlOREV3TWpVeU1URXpNek5hRncwek5ERXdNak15TVRFek16TmFNR\
      Vl4SERBYUJnTlZCQW9UCkUyUjVibUZ0YVdOc2FYTjBaVzVsY2kxdmNtY3hKakFrQmdOVkJBTU1IV\
      1I1Ym1GdGFXTnNhWE4wWlc1bGNpMWoKWVVBeE56STVPRGt3T0RFek1Ga3dFd1lIS29aSXpqMENBU\
      VlJS29aSXpqMERBUWNEUWdBRXJYclZmY0dkY243OAo4VzE3aWNldEpuck1Nc1Jsc2tBRXhyQTdSM\
      TNLeGpTVm1kOWFDb2FxOG5kdFlFOTBtVFpPcE9iNHdxOWw2ZXFiCjZxUS8vQTAvcUtOQ01FQXdEZ\
      1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWUQKVlIwT0JCWUVGS\
      lZ5K1hEeSt1SEdNSWxHWTB0VXNJYnlLQTBITUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSUhnVgple\
      mNMVG0vanZjemhFUFlGQ0IycVpnRHlNVHVzM2RLaDJPWmpodXQxQWlCcEZvd2JWQTVQNk51dU80N\
      lh1NUZDCmhsZmZWcG54a1FYVDNSdU5SKzI5R3c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"

users:
- name: "cluster1"
  user:
    token: "kubeconfig-user-pqkqld4p6t:tvfscr4jbkcv255522ctjhg2442gjfxnr8vw78z22crplkcnmn4zvz"


contexts:
- name: "cluster1"
  context:
    user: "cluster1"
    cluster: "cluster1"

current-context: "cluster1"
