apiVersion: v1
kind: Service
metadata:
  name: project3-app-service
spec:
  selector:
    app: project3-app
  ports:
    - protocol: TCP
      port: 80 # Exposed port
      targetPort: 8080 
      nodePort: 31416
  type: NodePort