apiVersion: v1
kind: Service
metadata:
  name: surveyproject-service
  labels: 
    app: surveyproject
spec:
  selector:
    app: surveyproject
  type: NodePort
  ports:
  - port: 8090
    protocol: TCP
    targetPort: 8090
    name: http
    nodePort: 31416
  - port: 443
    protocol: TCP
    name: https
    